name: PluginEX
version: 'v0.0.2'
authors: [ XIAOYI12 ]
main: io.newblock.pluginex.PluginEX
commands:
  pluginex:
    description: Plugin manager command.
    aliases:
      - pex
      - plugin
permissions:
  pluginex.admin.*:
    description: All permission.
    default: op
  pluginex.admin.command:
    description: Command use permission.
    default: op
  pluginex.admin.update:
    description: Update chat message.
    default: op
  pluginex.admin.gui:
    description: Show gui permission.
    default: op
